backend:
  name: github
  repo: satv2025/Papelera-Pierrastegui-NEW
  branch: main

media_folder: "assets/images"    # donde se guardan las imágenes en el repo
public_folder: "/assets/images"  # ruta pública usada por el frontend

media_library:
  name: uploadcare
  config:
    publicKey: "ebac821dcde16e4d8000"  # reemplaza con tu clave real si quieres subir imágenes

collections:
  - name: "products"
    label: "Productos"
    folder: "src/products"   # carpeta en el repo donde se guardarán los productos
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Precio", name: "price", widget: "number" }
      - { label: "Imagen", name: "image", widget: "image" }