backend:
  name: github
  repo: satv2025/Papelera-Pierrastegui-NEW
  branch: main

media_folder: ""           # se usará la raíz del repo o carpeta específica en GitHub
public_folder: ""          # se usará la misma ruta en la web

media_library:
  name: uploadcare
  config:
    publicKey: "ebac821dcde16e4d8000"  # reemplazá por tu clave de Uploadcare

collections:
  - name: "products"
    label: "Productos"
    folder: "src/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Precio", name: "price", widget: "number" }
      - { label: "Imagen", name: "image", widget: "image" }